services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=carlosedu44@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=carlito321
    ports:
      - "89:80"
    networks:
      - postgres-network

  postgres_user:
    image: postgres:latest
    container_name: postgres_container_user
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  postgres_room:
    image: postgres:latest
    container_name: postgres_container_room
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - postgres-network
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  postgres_reservation:
    image: postgres:latest
    container_name: postgres_container_reservation
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
