services:
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=carlosedu44@outlook.com
      - PGADMIN_DEFAULT_PASSWORD=carlito321
    ports:
      - "89:80"
    networks:
      - postgres-network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

networks:
  postgres-network:
    driver: bridge
